#!/bin/bash

update_description() {
  local file=$1
  local desc=$2
  # Replace the description line in the frontmatter
  sed -i '' "s|description=\".*\"|description=\"$desc\"|" "$file"
  echo "Updated: $file"
}

update_description "src/pages/da/advisory-services/raadgivning.astro" "Bitcoin-rådgivning og workshops for privatpersoner, virksomheder og foreninger i Danmark. Vi tilpasser os dit niveau og dine behov."
update_description "src/pages/da/blog/index.astro" "Bitcoin-artikler og blogindlæg på dansk. Dyk ned i historier, analyser og perspektiver fra det danske Bitcoin-fællesskab."
update_description "src/pages/da/faellesskab/bookmarks.astro" "En samling af de bedste Bitcoin-ressourcer, værktøjer og links — kurateret af det danske Bitcoin-fællesskab."
update_description "src/pages/da/faellesskab/initiativer-danmark.astro" "Overblik over Bitcoin-initiativer, projekter og fællesskaber i Danmark."
update_description "src/pages/da/faellesskab/mediekit.astro" "Enogtyve logoer, farver og grafiske materialer til download."
update_description "src/pages/da/faellesskab/playliste.astro" "Enogtyves Bitcoin-playliste på Spotify — musik til stacking og noderunning."
update_description "src/pages/da/faellesskab/support.astro" "Støt Enogtyve og det danske Bitcoin-fællesskab med sats via Lightning Network."
update_description "src/pages/da/idevaerksted/buidl.astro" "Idéer og projekter til dem der vil bygge på Bitcoin i Danmark."
update_description "src/pages/da/kom-igang/begreber-ord.astro" "Ordliste over Bitcoin-begreber og udtryk på dansk. Forstå sproget bag Bitcoin."
update_description "src/pages/da/kom-igang/bitcoin-boeger-dansk.astro" "De bedste Bitcoin-bøger tilgængelige på dansk — fra begynder til øvet."
update_description "src/pages/da/kom-igang/bitcoin-software.astro" "Overblik over Bitcoin-software til din computer, node og wallet."
update_description "src/pages/da/kom-igang/hardware-wallets.astro" "Guide til hardware wallets — den sikreste måde at opbevare dine bitcoin på."
update_description "src/pages/da/kom-igang/kob-bitcoin.astro" "Sådan køber du din første bitcoin i Danmark. Trin-for-trin guide til anskaffelse."
update_description "src/pages/da/kom-igang/opbevaring-af-bitcoin.astro" "Lær hvordan du opbevarer dine bitcoin sikkert — fra hot wallets til cold storage."
update_description "src/pages/da/kom-igang/optjen-bitcoin.astro" "Måder at optjene bitcoin på uden at købe dem — arbejde, salg og services."
update_description "src/pages/da/kom-igang/privatliv-best-practice.astro" "Best practice for privatliv og sikkerhed når du bruger Bitcoin."
update_description "src/pages/da/kom-igang/seed-phrase.astro" "Alt du skal vide om seed phrases og gendannelsesord — din Bitcoin-nøgle til fremtiden."
update_description "src/pages/da/laer-mere/bitcoin-blockchain.astro" "Forstå Bitcoin-blokkæden — hvordan transaktioner bekræftes og blokke skabes."
update_description "src/pages/da/laer-mere/bitcoin-og-din-forretning.astro" "Sådan accepterer din virksomhed Bitcoin som betaling. Praktisk guide til danske virksomheder."
update_description "src/pages/da/laer-mere/bitcoin-services-og-produkter.astro" "Overblik over Bitcoin-services og produkter du kan bruge i dag."
update_description "src/pages/da/laer-mere/ecash.astro" "Introduktion til eCash — digitale kontanter bygget på Bitcoin og Lightning."
update_description "src/pages/da/laer-mere/lightning-produkter-services.astro" "Produkter og services bygget på Lightning Network til brug i hverdagen."
update_description "src/pages/da/laer-mere/lightning-wallets.astro" "Overblik over de bedste Lightning wallets til hurtige og billige Bitcoin-betalinger."
update_description "src/pages/da/laer-mere/lightning.astro" "Introduktion til Bitcoin Lightning Network — hurtige og billige betalinger på Bitcoin."
update_description "src/pages/da/laer-mere/liquid.astro" "Hvad er Liquid Network? Bitcoins sidechain til hurtigere og mere private transaktioner."
update_description "src/pages/da/laer-mere/quotes-dansk.astro" "De bedste Bitcoin-citater oversat til dansk — til inspiration og orange-pilling."
update_description "src/pages/da/laer-mere/value4value.astro" "Hvad er Value4Value? En ny model for at støtte indhold direkte med bitcoin."
update_description "src/pages/da/mining/mining-for-opvarmning.astro" "Brug Bitcoin-mining til at varme dit hjem op. Praktisk guide til mining som varmekilde."
update_description "src/pages/da/mining/solo-mining.astro" "Guide til solo Bitcoin-mining — mød blokkæden på dine egne betingelser."
update_description "src/pages/da/podcasts/index.astro" "De bedste Bitcoin-podcasts på dansk og engelsk — kurateret af Enogtyve."
update_description "src/pages/da/rabat.astro" "Rabatter og tilbud på Bitcoin-produkter og services til Enogtyve-fællesskabet."
update_description "src/pages/da/udforsk/bitcoin-ressources.astro" "En samling af de bedste Bitcoin-ressourcer på nettet til videre læring."
update_description "src/pages/da/udforsk/cirkulaere-okonomier.astro" "Bitcoin cirkulære økonomier rundt om i verden — steder hvor bitcoin bruges i hverdagen."
update_description "src/pages/da/udforsk/freecities.astro" "Frie byer og samfund der bygger på Bitcoin og frihed fra statskontrol."
update_description "src/pages/da/udforsk/in-the-world.astro" "Bitcoin-fællesskaber og meetups verden over — find ligesindede hvor end du rejser."
update_description "src/pages/da/udforsk/konferencer.astro" "Overblik over Bitcoin-konferencer og events du kan deltage i."
update_description "src/pages/da/udforsk/moed-andre.astro" "Mød andre Bitcoinere når du rejser — en guide til at finde fællesskabet globalt."
update_description "src/pages/da/udforsk/nyheder.astro" "Seneste Bitcoin-nyheder og opdateringer fra det globale Bitcoin-fællesskab."
update_description "src/pages/da/udforsk/twentyoneworld.astro" "Twentyone.world — et globalt netværk af Bitcoin-fællesskaber og ressourcer."
update_description "src/pages/da/udforsk/udforsk.astro" "Udforsk Bitcoin-verdenen — konferencer, fællesskaber, cirkulære økonomier og meget mere."
update_description "src/pages/da/velkommen/fud-facts.astro" "FUD eller fakta? Vi gennemgår de mest udbredte myter om Bitcoin og svarer med facts."

echo "All descriptions updated!"
